default:
	cd messagelen && make
	cd twitter && make
	cd pling && make
	cd tell && make
	cd wolfram_alpha && make

clean:
	cd messagelen && make clean
	cd twitter && make clean
	cd pling && make clean
	cd tell && make clean
	cd wolfram_alpha && make clean
