default:
	cd messagelen && make
	cd twitter && make
	cd pling && make
	cd tell && make
	cd wolfram_alpha && make
	cd makerspace.se && make
	cd utf8valid && make
	cd log && make
	cd math && make
	cd random_unicode && make

clean:
	cd messagelen && make clean
	cd twitter && make clean
	cd pling && make clean
	cd tell && make clean
	cd wolfram_alpha && make clean
	cd makerspace.se && make clean
	cd utf8valid && make clean
	cd log && make clean
	cd math && make clean
	cd random_unicode && make clean
