default:
	cd fanbot && make
	cd config && make
	cd network_plain && make
	cd network_ssl && make

clean:
	cd fanbot && make clean
	cd config && make clean
	cd network_plain && make clean
	cd network_ssl && make clean
